openapi: 3.0.3
info:
  title: API REST de Videojuegos
  version: 1.0.0
  description: API para gestionar videojuegos, consolas y empresas
servers:
  - url: http://localhost:3000
    description: Servidor local de desarrollo

paths:
  /videojuegos:
    get:
      summary: Obtener lista de videojuegos
      responses:
        "200":
          description: Lista de videojuegos
    post:
      summary: Crear un videojuego
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Videojuego"
      responses:
        "201":
          description: Videojuego creado con éxito

  /videojuegos/{id}:
    get:
      summary: Obtener información de un videojuego por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Información del videojuego
    put:
      summary: Actualizar un videojuego
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Videojuego"
      responses:
        "200":
          description: Videojuego actualizado
    delete:
      summary: Eliminar un videojuego
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Videojuego eliminado

  /consolas:
    get:
      summary: Obtener lista de consolas
      responses:
        "200":
          description: Lista de consolas
    post:
      summary: Crear una consola
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Consola"
      responses:
        "201":
          description: Consola creada con éxito

  /consolas/{id}:
    get:
      summary: Obtener información de una consola
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Información de la consola
    put:
      summary: Actualizar una consola
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Consola"
      responses:
        "200":
          description: Consola actualizada
    delete:
      summary: Eliminar una consola
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Consola eliminada

  /consolas/{id}/videojuegos:
    get:
      summary: Obtener videojuegos disponibles en una consola
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Lista de videojuegos disponibles en la consola
    post:
      summary: Agregar un videojuego a una consola
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Videojuego"
      responses:
        "201":
          description: Videojuego agregado a la consola
    put:
      summary: Actualizar un videojuego en una consola
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: videojuegoId
          in: query
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Videojuego"
      responses:
        "200":
          description: Videojuego actualizado en la consola
    delete:
      summary: Eliminar un videojuego de una consola
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: videojuegoId
          in: query
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Videojuego eliminado de la consola

  /empresas:
    get:
      summary: Obtener lista de empresas desarrolladoras
      responses:
        "200":
          description: Lista de empresas
    post:
      summary: Crear una empresa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Empresa"
      responses:
        "201":
          description: Empresa creada con éxito

  /empresas/{id}:
    get:
      summary: Obtener información de una empresa
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Información de la empresa
    put:
      summary: Actualizar una empresa
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Empresa"
      responses:
        "200":
          description: Empresa actualizada
    delete:
      summary: Eliminar una empresa
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Empresa eliminada

  /empresas/{id}/videojuegos:
    get:
      summary: Obtener videojuegos desarrollados por una empresa
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Lista de videojuegos desarrollados por la empresa
    post:
      summary: Agregar un videojuego a la empresa
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Videojuego"
      responses:
        "201":
          description: Videojuego agregado a la empresa
    put:
      summary: Actualizar un videojuego de la empresa
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: videojuegoId
          in: query
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Videojuego"
      responses:
        "200":
          description: Videojuego actualizado para la empresa
    delete:
      summary: Eliminar un videojuego de la empresa
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: videojuegoId
          in: query
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Videojuego eliminado de la empresa

components:
  schemas:
    Videojuego:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string

    Consola:
      type: object
      properties:
        id:
          type: string
        nombre:
          type: string

    Empresa:
      type: object
      properties:
        id:
          type: string
        nombre:
          type: string
