openapi: 3.0.3
info:
  title: API REST de Videojuegos
  version: 1.0.0
  description: API para gestionar videojuegos, consolas y empresas
servers:
  - url: http://localhost:3000
    description: Servidor local de desarrollo

paths:
  /videojuegos:
    get:
      summary: Obtener lista de videojuegos
      description: Devuelve la lista de videojuegos con posibilidad de filtrado
      responses:
        "200":
          description: Lista de videojuegos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Videojuego"
        "400":
          description: Algún parámetro no es válido
    post:
      summary: Crear un videojuego
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Videojuego"
      responses:
        "201":
          description: Videojuego creado con éxito
        "400":
          description: JSON no válido
        "401":
          description: No estamos autorizados
        "403":
          description: No tenemos permiso

  /videojuegos/{id}:
    get:
      summary: Obtener información de un videojuego por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Información del videojuego
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Videojuego"
        "404":
          description: ID no válido

  /videojuegos/{id}/consolas:
    get:
      summary: Obtener consolas en las que está disponible un videojuego
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Consolas disponibles para el videojuego
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Consola"

  /videojuegos/{id}/empresa:
    get:
      summary: Obtener la empresa desarrolladora de un videojuego
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Empresa desarrolladora del videojuego
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empresa"

  /consolas:
    get:
      summary: Obtener lista de consolas
      description: Devuelve la lista de consolas registradas
      responses:
        "200":
          description: Lista de consolas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Consola"

  /consolas/{id}:
    get:
      summary: Obtener información de una consola por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Información de la consola
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Consola"
        "404":
          description: ID no válido

  /empresas:
    get:
      summary: Obtener lista de empresas desarrolladoras de videojuegos
      responses:
        "200":
          description: Lista de empresas desarrolladoras
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Empresa"

  /empresas/{id}:
    get:
      summary: Obtener información de una empresa desarrolladora
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Información de la empresa
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empresa"
        "404":
          description: ID no válido

components:
  schemas:
    Videojuego:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string
        fecha_lanzamiento:
          type: string
          format: date
        dispositivo:
          type: string
        precio:
          type: number
        version:
          type: string
        PEGI:
          type: string
        descripcion:
          type: string
        empresa:
          type: string
        multijugador:
          type: boolean
        idioma:
          type: string

    Consola:
      type: object
      properties:
        id:
          type: string
        nombre:
          type: string

    Empresa:
      type: object
      properties:
        id:
          type: string
        nombre:
          type: string
